# Generated by Django 6.0 on 2025-12-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_from_note',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='note_part_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='note_part_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
