# Generated by Django 5.2.8 on 2026-01-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todo_created_from_note_todo_note_part_date_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='todo',
            constraint=models.UniqueConstraint(condition=models.Q(('created_from_note', True)), fields=('created_from_note', 'note_part_date', 'note_part_text'), name='unique_note_parts_when_created_from_note'),
        ),
    ]
