# Generated by Django 5.2.8 on 2025-11-20 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking', '0002_alter_note_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(default=None, max_length=50)),
                ('subject', models.CharField(blank=True, default=None, max_length=50)),
                ('tags', models.CharField(blank=True, default=None, max_length=50)),
                ('content', models.TextField(default=None)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note_taking.note')),
            ],
        ),
    ]
