# Generated by Django 5.2.8 on 2025-12-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking', '0003_notepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-17'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='raw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
