# Generated by Django 5.2.8 on 2025-12-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking', '0004_note_created_note_raw_note_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
