# Generated by Django 5.2.8 on 2025-12-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking', '0005_note_is_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepart',
            name='content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='notepart',
            name='subject',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notepart',
            name='tags',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
