# Generated by Django 5.2.8 on 2025-12-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking', '0006_alter_notepart_content_alter_notepart_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notepart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notepart',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
