# Generated by Django 5.2.8 on 2025-12-17 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking', '0007_notepart_created_notepart_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepart',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='note_taking.note'),
        ),
    ]
