# Generated by Django 5.2.8 on 2025-12-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking', '0008_alter_notepart_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepart',
            name='tags',
            field=models.JSONField(),
        ),
    ]
