# Generated by Django 5.2.8 on 2025-12-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking', '0009_alter_notepart_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='projects',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='subjects',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notepart',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
