# Generated by Django 5.2.8 on 2025-12-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking', '0010_note_projects_note_subjects_note_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='note',
            name='subjects',
        ),
    ]
