# Generated by Django 5.2.8 on 2025-12-18 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking', '0011_project_remove_note_projects_remove_note_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepart',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='note_parts', to='note_taking.project'),
        ),
    ]
