# Generated by Django 5.2.8 on 2026-04-13 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking', '0012_alter_notepart_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotePartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, upload_to='note_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('original_path', models.CharField(max_length=255)),
                ('note_part', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='note_taking.note')),
            ],
        ),
    ]
