# Generated by Django 5.2.8 on 2026-04-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking', '0014_alter_notepartimage_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepartimage',
            name='original_path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
