# Generated by Django 5.2.8 on 2026-04-14 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking', '0015_alter_notepartimage_original_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notepartimage',
            name='alt_text',
        ),
    ]
