# Generated by Django 5.2.8 on 2026-04-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking', '0016_remove_notepartimage_alt_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notepartimage',
            name='note_part',
        ),
    ]
